            //---- Users ---------------------//

//FETCH USERS
export const FETCH_USERS_INITIATE = "FETCH_USERS_INITIATE";
export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
//UPDATE USER
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
export const UPDATE_USER_ROLE = "UPDATE_USER_ROLE";
export const SAVE_USER_INIT = "SAVE_USER_INIT";
export const SAVE_USER_START = "SAVE_USER_START";
export const SAVE_USER_SUCESS = "SAVE_USER_SUCESS";
export const SAVE_USER_FAIL = "SAVE_USER_FAIL";
//DELTE USER
export const DELETE_USER_INIT = "DELETE_USER_INIT";
export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

            //--- Store --------------------//
    // CATEGORY
//FETCH CATEGORIES
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_START = "FETCH_CATEGORY_START"; 
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAIL = "FETCH_CATEGORY_FAIL";
//ADD CATEGORY
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_START = "ADD_CATEGORY_START";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
//DELETE CATEGORY
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
//UPDATE CATEGORY
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_START = "UPDATE_CATEGORY_START";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

    //PRODUCT

//FETCH PRODUCTS
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START"; 
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";
//ADD PRODUCT
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
//DELETE PRODUCT
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
//UPDATE PRODUCT
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
