            //---- Users ---------------------//

//FETCH USERS
export const FETCH_USERS_INITIATE = "FETCH_USERS_INITIATE";
export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
//UPDATE USER
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
export const UPDATE_USER_ROLE = "UPDATE_USER_ROLE";
export const SAVE_USER_INIT = "SAVE_USER_INIT";
export const SAVE_USER_START = "SAVE_USER_START";
export const SAVE_USER_SUCESS = "SAVE_USER_SUCESS";
export const SAVE_USER_FAIL = "SAVE_USER_FAIL";
//DELTE USER
export const DELETE_USER_INIT = "DELETE_USER_INIT";
export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

            //--- Store --------------------//
    // CATEGORY
//FETCH CATEGORIES
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_START = "FETCH_CATEGORY_START"; 
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAIL = "FETCH_CATEGORY_FAIL";
//ADD CATEGORY
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_START = "ADD_CATEGORY_START";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
//DELETE CATEGORY
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
//UPDATE CATEGORY
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_START = "UPDATE_CATEGORY_START";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

    //PRODUCT

//FETCH PRODUCTS
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START"; 
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";
//ADD PRODUCT
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
//DELETE PRODUCT
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
//UPDATE PRODUCT
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

    //ORDER
//ORDER BUILDER
export const SET_ORDER = "SET_ORDER";
export const SET_ORDER_INFO = "SET_ORDER_INFO";
export const RESET_ORDER_INFO = "RESET_ORDER_INFO";
export const ADD_ORDER_DETAIL = "ADD_ORDER_DETAIL";
export const REMOVE_ORDER_DETAIL = "REMOVE_ORDER_DETAIL";
export const UPDATE_ORDER_DETAIL = "UPDATE_ORDER_DETAIL";
export const SET_ORDER_DETAILS = "SET_ORDER_DETAILS";
//FETCH ORDERS
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START"; 
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
//ADD ORDER
export const ADD_ORDER = "ADD_ORDER";
export const ADD_ORDER_START = "ADD_ORDER_START";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";
//DELETE ORDER
export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_START = "DELETE_ORDER_START";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
//UPDATE ORDER
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_START = "UPDATE_ORDER_START";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";
// Order List Page
export const INCREMENT_PAGE = "INCREMENT_PAGE";
export const DECREMENT_PAGE = "DECREMENT_PAGE";
// Order Details
export const FETCH_ORDERS_DETAILS = "FETCH_ORDERS_DETAILS";
export const FETCH_ORDERS_DETAILS_START = "FETCH_ORDERS_DETAILS_START";
export const FETCH_ORDERS_DETAILS_FAIL = "FETCH_ORDERS_DETAILS_FAIL";
export const FETCH_ORDERS_DETAILS_SUCCESS = "FETCH_ORDERS_DETAILS_SUCCESS";
export const UPDATE_DETAIL_STATE = "UPDATE_DETAIL_STATE";
export const UPDATE_DETAIL_STATE_START = "UPDATE_DETAIL_STATE_START";
export const UPDATE_DETAIL_STATE_FAIL = "UPDATE_DETAIL_STATE_FAIL";
export const UPDATE_DETAIL_STATE_SUCCESS = "UPDATE_DETAIL_STATE_SUCCESS";