// Users action types
export const FETCH_USERS_INITIATE = "FETCH_USERS_INITIATE";
export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
export const UPDATE_USER_ROLE = "UPDATE_USER_ROLE";
export const SAVE_USER_INIT = "SAVE_USER_INIT";
export const SAVE_USER_START = "SAVE_USER_START";
export const SAVE_USER_SUCESS = "SAVE_USER_SUCESS";
export const SAVE_USER_FAIL = "SAVE_USER_FAIL";
export const DELETE_USER_INIT = "DELETE_USER_INIT";
export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
// User action types
export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

